version: '3.9'

services:
  app-db:
    container_name: kolloid_db_dev
    image: postgres:15-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: kolloid
      POSTGRES_USER: kolloid_user
      POSTGRES_PASSWORD: tiger
      POSTGRES_PORT: 5432
# This will initialize the database but conflict with flyway in the server.
#    volumes:
#      - ../../db/src/main/resources/flyway/:/docker-entrypoint-initdb.d/

networks:
  default:
    name: app_dev_network
